.\"
.\" Introduction man page for libcups.
.\"
.\" Copyright © 2025 by OpenPrinting.
.\"
.\" Licensed under Apache License v2.0.  See the file "LICENSE" for more
.\" information.
.\"
.TH libcups 3 "CUPS" "2025-03-04" "OpenPrinting"
.SH NAME
libcups \- cups api library
.SH DESCRIPTION
.SH SEE ALSO
.BR cups (1)
.SH COPYRIGHT
Copyright \[co] 2025 by OpenPrinting.
