#
# 8-up test printer configuration file.
#
# Copyright © 2026 by OpenPrinting.
#
# Licensed under Apache License v2.0.  See the file "LICENSE" for more
# information.
#

ATTR mimeMediaType document-format-default application/pdf
ATTR mimeMediaType document-format-supported application/pdf

ATTR integer number-up-default 1
ATTR integer number-up-supported 1,2,4,6,8,9,12,16
